server:
  port: 8084

spring:
  application:
    name: quiz-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:quiz_db}
    username: ${POSTGRES_USER:eha}
    password: ${POSTGRES_PASSWORD:eha_password}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
